<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lobbycal"
 *
 * Auto generated by Extension Builder 2015-11-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'LobbyCal',
	'description' => 'Displays LobbyCal Calendar',
	'category' => 'plugin',
	'author' => 'Transparency International EU',
	'author_email' => 'brussels@transparency.org',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.0.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '4.5.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);